/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assests/Models/xfighter1.glb -o temp.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_62: THREE.Mesh
    Object_63: THREE.Mesh
  }
  materials: {
    Default: THREE.MeshStandardMaterial
    Stick: THREE.MeshStandardMaterial
    xwingCanopy: THREE.MeshStandardMaterial
    xwingCanopyGaskets: THREE.MeshStandardMaterial
    xwingCanopyGlassInner: THREE.MeshStandardMaterial
    xwingCanopyGlassOuter: THREE.MeshStandardMaterial
    xwingCockpitBluePlastic: THREE.MeshStandardMaterial
    xwingCockpitBrass: THREE.MeshStandardMaterial
    xwingCockpitChair: THREE.MeshStandardMaterial
    xwingCockpitCyanPlastic: THREE.MeshStandardMaterial
    xwingCockpitInterior: THREE.MeshStandardMaterial
    xwingCockpitLeftMonitor: THREE.MeshStandardMaterial
    xwingCockpitMainMonitor: THREE.MeshStandardMaterial
    xwingCockpitMonitorGreen: THREE.MeshStandardMaterial
    xwingCockpitMonitorYellow: THREE.MeshStandardMaterial
    xwingCockpitOrangePlastic: THREE.MeshStandardMaterial
    xwingCockpitRedLights: THREE.MeshStandardMaterial
    xwingCockpitRedPlastic: THREE.MeshStandardMaterial
    xwingCockpitRightMonitor: THREE.MeshStandardMaterial
    xwingCockpitWhiteLights: THREE.MeshStandardMaterial
    xwingCockpitYellowPlastic: THREE.MeshStandardMaterial
    xwingNose: THREE.MeshStandardMaterial
    xwingNurnies: THREE.MeshStandardMaterial
    xwingCockpitAluminum: THREE.MeshStandardMaterial
    xwingCockpitBlackPlastic: THREE.MeshStandardMaterial
    xwingCockpitGreenLights: THREE.MeshStandardMaterial
    xwingCockpitInteriorDetails: THREE.MeshStandardMaterial
    xwingCockpitSilver: THREE.MeshStandardMaterial
    xwingCockpitWhitePlastic: THREE.MeshStandardMaterial
    xwingEngineGlow: THREE.MeshStandardMaterial
    xwingEngineGlowTrans: THREE.MeshStandardMaterial
    xwingEngineInterior: THREE.MeshStandardMaterial
    xwingEngines: THREE.MeshStandardMaterial
    xwingFuselage: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/xfighter1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.281]} rotation={[-Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Default} position={[0.005, 0.027, 0.841]} scale={0.801} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Stick} position={[0.013, 0.001, 0.734]} scale={0.019} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.xwingCanopy} position={[0, 0.01, 0.85]} scale={0.785} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.xwingCanopyGaskets} position={[0, -1.102, 0.856]} scale={0.572} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.xwingCanopyGlassInner} position={[0, -1.099, 0.849]} scale={0.568} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.xwingCanopyGlassInner} position={[0, 0.023, 0.853]} scale={0.744} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.xwingCanopyGlassOuter} position={[0, -1.064, 0.855]} scale={0.577} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.xwingCanopyGlassOuter} position={[0, 0.024, 0.858]} scale={0.745} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.xwingCockpitBluePlastic} position={[0.153, 0.363, 0.783]} scale={0.053} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.xwingCockpitBrass} position={[0.013, -0.785, 0.811]} scale={0.395} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.xwingCockpitChair} position={[0, -0.316, 0.553]} scale={0.397} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.xwingCockpitCyanPlastic} position={[-0.031, -0.295, 0.619]} scale={0.543} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.xwingCockpitInterior} position={[0, 0.085, 0.372]} scale={0.84} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.xwingCockpitInterior} position={[0.001, -0.767, 1.043]} scale={0.389} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.xwingCockpitLeftMonitor} position={[-0.162, 0.182, 0.704]} scale={0.046} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.xwingCockpitMainMonitor} position={[0, 0.187, 0.696]} scale={0.083} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.xwingCockpitMonitorGreen} position={[0, 0.088, 0.431]} scale={0.046} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.xwingCockpitMonitorYellow} position={[-0.043, -0.206, 0.493]} scale={0.419} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.xwingCockpitOrangePlastic} position={[0.13, 0.145, 0.786]} scale={0.225} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.xwingCockpitRedLights} position={[0.01, -0.082, 0.639]} scale={0.534} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.xwingCockpitRedPlastic} position={[-0.02, -0.068, 0.581]} scale={0.603} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.xwingCockpitRightMonitor} position={[0.163, 0.182, 0.704]} scale={0.046} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.xwingCockpitWhiteLights} position={[0.003, 0.08, 0.556]} scale={0.774} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.xwingCockpitYellowPlastic} position={[0.021, -0.246, 0.524]} scale={0.417} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.xwingNose} position={[0, 4.985, 0.129]} scale={0.408} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.xwingNurnies} position={[0, -5.679, 0.114]} scale={0.515} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.xwingCockpitAluminum} position={[-0.012, -0.914, 0.789]} scale={0.385} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.xwingCockpitAluminum} position={[0, -0.272, 0.539]} scale={0.442} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.xwingCockpitBlackPlastic} position={[-0.101, -0.513, 0.662]} scale={0.496} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.xwingCockpitBlackPlastic} position={[-0.026, -0.911, 0.835]} scale={0.389} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.xwingCockpitBlackPlastic} position={[0.006, 0.087, 0.394]} scale={0.838} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.xwingCockpitGreenLights} position={[-0.047, -0.169, 0.689]} scale={0.638} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.xwingCockpitInteriorDetails} position={[-0.376, -1.156, 0.729]} scale={0.278} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.xwingCockpitInteriorDetails} position={[0.073, 0.067, 0.382]} scale={0.848} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.xwingCockpitSilver} position={[0.027, 0.074, 0.584]} scale={0.843} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.xwingCockpitSilver} position={[0, -1.004, 0.838]} scale={0.348} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.xwingCockpitWhitePlastic} position={[-0.028, -0.022, 0.584]} scale={0.786} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.xwingEngineGlow} position={[0, -5.291, 0]} scale={1.61} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.xwingEngineGlowTrans} position={[0, -5.517, 0]} scale={1.659} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.xwingEngineInterior} position={[0, -2.917, 0]} scale={1.884} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.xwingEngineInterior} position={[0, -2.917, 0]} scale={1.884} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.xwingEngineInterior} position={[0, -5.545, 0]} scale={1.719} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.xwingEngineInterior} position={[0, -5.545, 0]} scale={1.719} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.xwingEngineInterior} position={[0, -2.818, 0]} scale={1.885} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.xwingEngines} position={[0, -3.457, 0]} scale={2.025} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.xwingEngines} position={[0, -3.457, 0]} scale={2.025} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.xwingEngines} position={[0, -5.048, 0]} scale={1.773} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.xwingEngines} position={[-0.002, -4.869, 0]} scale={1.771} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.xwingEngines} position={[0, -5.048, 0]} scale={1.773} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.xwingEngines} position={[0.002, -4.869, 0]} scale={1.771} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.xwingFuselage} position={[0, -3.52, 0.487]} scale={2.002} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.xwingFuselage} position={[0, 0.239, 0.062]} scale={6.032} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.xwingFuselage} position={[0, -1.089, 0.826]} scale={0.609} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.xwingFuselage} position={[0, 0.04, 0.83]} scale={0.82} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.xwingNurnies} position={[0, -5.62, -0.107]} scale={0.752} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.xwingNurnies} position={[0, -3.083, 0.319]} scale={2.467} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.xwingNurnies} position={[-0.024, -2.882, 0.703]} scale={2.227} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.xwingNurnies} position={[0, -3.102, 0.704]} scale={2.448} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.xwingEngines} position={[0, -1.075, 0]} scale={5.425} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.xwingEngines} position={[0, -1.075, 0]} scale={5.425} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.xwingEngines} position={[0, -3.706, 0]} scale={5.49} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.xwingEngines} position={[0, -3.706, 0]} scale={5.49} />
      </group>
    </group>
  )
}

useGLTF.preload('/xfighter1.glb')
