/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assests/Models/30654_-_x-wing_starfighter.glb -o src/components/XWingModelGenerated.tsx 
Author: Avery (https://sketchfab.com/averyre)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/30654-x-wing-starfighter-d268cc47d38d42b8ba7d435bc75d57db
Title: 30654 - X-Wing Starfighter
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Base: THREE.Mesh
    Base_1: THREE.Mesh
    Base_2: THREE.Mesh
    Base_3: THREE.Mesh
    Base_4: THREE.Mesh
    Base_5: THREE.Mesh
    Base_6: THREE.Mesh
    Base_7: THREE.Mesh
    Base_8: THREE.Mesh
    Base_9: THREE.Mesh
    Base_10: THREE.Mesh
    Base_11: THREE.Mesh
    Base_12: THREE.Mesh
    Base_13: THREE.Mesh
    Base_14: THREE.Mesh
    Base_15: THREE.Mesh
    Base_16: THREE.Mesh
    Base_17: THREE.Mesh
    Base_18: THREE.Mesh
    Base_19: THREE.Mesh
    Base_20: THREE.Mesh
    Base_21: THREE.Mesh
    Base_22: THREE.Mesh
    Base_23: THREE.Mesh
    Base_24: THREE.Mesh
    Base_25: THREE.Mesh
    Base_26: THREE.Mesh
    Base_27: THREE.Mesh
    Base_28: THREE.Mesh
    Base_29: THREE.Mesh
    Base_30: THREE.Mesh
    Base_31: THREE.Mesh
    Base_32: THREE.Mesh
    Base_33: THREE.Mesh
    Base_34: THREE.Mesh
    Base_35: THREE.Mesh
    Base_36: THREE.Mesh
    Base_37: THREE.Mesh
    Base_38: THREE.Mesh
    Base_39: THREE.Mesh
    Base_40: THREE.Mesh
    Base_41: THREE.Mesh
    Base_42: THREE.Mesh
    Base_43: THREE.Mesh
    Base_44: THREE.Mesh
    Base_45: THREE.Mesh
    Base_46: THREE.Mesh
    Base_47: THREE.Mesh
    Base_48: THREE.Mesh
    Base_49: THREE.Mesh
    Base_50: THREE.Mesh
    Base_51: THREE.Mesh
    Base_52: THREE.Mesh
    Base_53: THREE.Mesh
    Base_54: THREE.Mesh
    Base_55: THREE.Mesh
    Base_56: THREE.Mesh
    Base_57: THREE.Mesh
    Base_58: THREE.Mesh
    Base_59: THREE.Mesh
    Base_60: THREE.Mesh
    Base_61: THREE.Mesh
    Base_62: THREE.Mesh
    Base_63: THREE.Mesh
    Base_64: THREE.Mesh
    Base_65: THREE.Mesh
    Base_66: THREE.Mesh
    Base_67: THREE.Mesh
    Base_68: THREE.Mesh
    Base_69: THREE.Mesh
    Base_70: THREE.Mesh
    Base_71: THREE.Mesh
    Base_72: THREE.Mesh
    Base_73: THREE.Mesh
    Base_74: THREE.Mesh
    Base_75: THREE.Mesh
    Base_76: THREE.Mesh
    Base_77: THREE.Mesh
    Base_78: THREE.Mesh
    Base_79: THREE.Mesh
    Base_80: THREE.Mesh
    Base_81: THREE.Mesh
    Base_82: THREE.Mesh
    Base_83: THREE.Mesh
    Base_84: THREE.Mesh
    Base_85: THREE.Mesh
    Base_86: THREE.Mesh
    Base_87: THREE.Mesh
    Base_88: THREE.Mesh
    Base_89: THREE.Mesh
    Base_90: THREE.Mesh
    Base_91: THREE.Mesh
    Base_92: THREE.Mesh
    Base_93: THREE.Mesh
    Base_94: THREE.Mesh
    Base_95: THREE.Mesh
    Base_96: THREE.Mesh
    Base_97: THREE.Mesh
    Base_98: THREE.Mesh
    Base_99: THREE.Mesh
    Base_100: THREE.Mesh
    Base_101: THREE.Mesh
    Base_102: THREE.Mesh
    Base_103: THREE.Mesh
    Base_104: THREE.Mesh
    Base_105: THREE.Mesh
    Base_106: THREE.Mesh
    Base_107: THREE.Mesh
    Base_108: THREE.Mesh
    Base_109: THREE.Mesh
    Base_110: THREE.Mesh
    Base_111: THREE.Mesh
    Base_112: THREE.Mesh
    Base_113: THREE.Mesh
    Base_114: THREE.Mesh
    Base_115: THREE.Mesh
    Base_116: THREE.Mesh
    Base_117: THREE.Mesh
    Base_118: THREE.Mesh
    Base_119: THREE.Mesh
    Base_120: THREE.Mesh
    Base_121: THREE.Mesh
    Base_122: THREE.Mesh
    Base_123: THREE.Mesh
    Base_124: THREE.Mesh
    Base_125: THREE.Mesh
    Base_126: THREE.Mesh
    Base_127: THREE.Mesh
    Base_128: THREE.Mesh
    Base_129: THREE.Mesh
    Base_130: THREE.Mesh
    Base_131: THREE.Mesh
    Base_132: THREE.Mesh
    Base_133: THREE.Mesh
    Base_134: THREE.Mesh
    Base_135: THREE.Mesh
    Base_136: THREE.Mesh
    Base_137: THREE.Mesh
    Base_138: THREE.Mesh
    Base_139: THREE.Mesh
    Base_140: THREE.Mesh
    Base_141: THREE.Mesh
    Base_142: THREE.Mesh
    Base_143: THREE.Mesh
    Base_144: THREE.Mesh
    Base_145: THREE.Mesh
    Base_146: THREE.Mesh
    Base_147: THREE.Mesh
    Base_148: THREE.Mesh
    Base_149: THREE.Mesh
    Base_150: THREE.Mesh
    Base_151: THREE.Mesh
    Base_152: THREE.Mesh
    Base_153: THREE.Mesh
    Base_154: THREE.Mesh
    Base_155: THREE.Mesh
    Base_156: THREE.Mesh
    Base_157: THREE.Mesh
    Base_158: THREE.Mesh
    Base_159: THREE.Mesh
    Base_160: THREE.Mesh
    Base_161: THREE.Mesh
    Base_162: THREE.Mesh
    Base_163: THREE.Mesh
    Base_164: THREE.Mesh
    Base_165: THREE.Mesh
    Base_166: THREE.Mesh
    Base_167: THREE.Mesh
    Base_168: THREE.Mesh
    Base_169: THREE.Mesh
    Base_170: THREE.Mesh
    Base_171: THREE.Mesh
    Base_172: THREE.Mesh
    Base_173: THREE.Mesh
    Base_174: THREE.Mesh
    Base_175: THREE.Mesh
    Base_176: THREE.Mesh
    Base_177: THREE.Mesh
    Base_178: THREE.Mesh
    Base_179: THREE.Mesh
    Base_180: THREE.Mesh
    Base_181: THREE.Mesh
    Base_182: THREE.Mesh
    Base_183: THREE.Mesh
    Base_184: THREE.Mesh
    Base_185: THREE.Mesh
    Base_186: THREE.Mesh
    Base_187: THREE.Mesh
    Base_188: THREE.Mesh
    Base_189: THREE.Mesh
    Base_190: THREE.Mesh
    Base_191: THREE.Mesh
    Base_192: THREE.Mesh
    Base_193: THREE.Mesh
    Base_194: THREE.Mesh
    Base_195: THREE.Mesh
    Base_196: THREE.Mesh
    Base_197: THREE.Mesh
    Base_198: THREE.Mesh
    Base_199: THREE.Mesh
    Base_200: THREE.Mesh
  }
  materials: {
    ['SOLID-WHITE']: THREE.MeshStandardMaterial
    ['SOLID-WHITE_0']: THREE.MeshStandardMaterial
    ['SOLID-DARK_RED']: THREE.MeshStandardMaterial
    ['SOLID-DARK_RED_0']: THREE.MeshStandardMaterial
    ['SOLID-LIGHT_BLUISH_GRAY']: THREE.MeshStandardMaterial
    ['METAL-SILVER']: THREE.MeshStandardMaterial
    ['METAL-SILVER_0']: THREE.MeshStandardMaterial
    ['TRANS-BROWN']: THREE.MeshStandardMaterial
    ['SOLID-LIGHT_BLUISH_GRAY_0']: THREE.MeshStandardMaterial
    ['PEARL-DARK_GRAY']: THREE.MeshStandardMaterial
    ['SOLID-DARK_BLUISH_GRAY']: THREE.MeshStandardMaterial
    ['SOLID-BLACK']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/30654_-_x-wing_starfighter.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[0, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.Base.geometry} material={materials['SOLID-WHITE']} position={[-170, -49.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_1.geometry} material={materials['SOLID-WHITE_0']} position={[-199.906, -49.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_2.geometry} material={materials['SOLID-WHITE_0']} position={[-179.968, -49.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_3.geometry} material={materials['SOLID-WHITE_0']} position={[-160.031, -49.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_4.geometry} material={materials['SOLID-WHITE_0']} position={[-140.094, -49.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_5.geometry} material={materials['SOLID-WHITE']} position={[-150, -57.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_6.geometry} material={materials['SOLID-WHITE_0']} position={[-179.906, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_7.geometry} material={materials['SOLID-WHITE_0']} position={[-159.969, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_8.geometry} material={materials['SOLID-WHITE_0']} position={[-140.031, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_9.geometry} material={materials['SOLID-WHITE_0']} position={[-120.094, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_10.geometry} material={materials['SOLID-WHITE']} position={[-210, -57.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_11.geometry} material={materials['SOLID-WHITE_0']} position={[-200.062, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_12.geometry} material={materials['SOLID-WHITE_0']} position={[-219.937, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_13.geometry} material={materials['SOLID-WHITE']} position={[-90, -49.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_14.geometry} material={materials['SOLID-WHITE_0']} position={[-119.906, -49.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_15.geometry} material={materials['SOLID-WHITE_0']} position={[-99.969, -49.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_16.geometry} material={materials['SOLID-WHITE_0']} position={[-80.032, -49.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_17.geometry} material={materials['SOLID-WHITE_0']} position={[-60.094, -49.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_18.geometry} material={materials['SOLID-WHITE']} position={[-70, -57.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_19.geometry} material={materials['SOLID-WHITE_0']} position={[-99.906, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_20.geometry} material={materials['SOLID-WHITE_0']} position={[-79.969, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_21.geometry} material={materials['SOLID-WHITE_0']} position={[-60.032, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_22.geometry} material={materials['SOLID-WHITE_0']} position={[-40.094, -57.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_23.geometry} material={materials['SOLID-DARK_RED']} position={[-190, -65.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_24.geometry} material={materials['SOLID-DARK_RED_0']} position={[-219.906, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_25.geometry} material={materials['SOLID-DARK_RED_0']} position={[-199.968, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_26.geometry} material={materials['SOLID-DARK_RED_0']} position={[-180.031, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_27.geometry} material={materials['SOLID-DARK_RED_0']} position={[-160.094, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_28.geometry} material={materials['SOLID-DARK_RED']} position={[-110, -65.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_29.geometry} material={materials['SOLID-DARK_RED_0']} position={[-139.906, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_30.geometry} material={materials['SOLID-DARK_RED_0']} position={[-119.969, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_31.geometry} material={materials['SOLID-DARK_RED_0']} position={[-100.031, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_32.geometry} material={materials['SOLID-DARK_RED_0']} position={[-80.094, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_33.geometry} material={materials['SOLID-WHITE']} position={[-50, -65.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_34.geometry} material={materials['SOLID-WHITE_0']} position={[-40.063, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_35.geometry} material={materials['SOLID-WHITE_0']} position={[-59.938, -65.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_36.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-210, -65.304, 20]} rotation={[0, -Math.PI / 2, 0]} scale={[0.987, 0.984, 0.994]} />
            <mesh geometry={nodes.Base_37.geometry} material={materials['SOLID-WHITE']} position={[-90, -73.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_38.geometry} material={materials['SOLID-WHITE_0']} position={[-119.906, -73.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_39.geometry} material={materials['SOLID-WHITE_0']} position={[-99.969, -73.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_40.geometry} material={materials['SOLID-WHITE_0']} position={[-80.032, -73.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_41.geometry} material={materials['SOLID-WHITE_0']} position={[-60.094, -73.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_42.geometry} material={materials['SOLID-WHITE']} position={[-170, -73.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_43.geometry} material={materials['SOLID-WHITE_0']} position={[-199.906, -73.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_44.geometry} material={materials['SOLID-WHITE_0']} position={[-179.968, -73.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_45.geometry} material={materials['SOLID-WHITE_0']} position={[-160.031, -73.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_46.geometry} material={materials['SOLID-WHITE_0']} position={[-140.094, -73.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_47.geometry} material={materials['METAL-SILVER']} position={[-40, -73.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_48.geometry} material={materials['METAL-SILVER_0']} position={[-40, -73.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_49.geometry} material={materials['SOLID-WHITE']} position={[-70, -81.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_50.geometry} material={materials['SOLID-WHITE_0']} position={[-60.063, -81.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_51.geometry} material={materials['SOLID-WHITE_0']} position={[-79.938, -81.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_52.geometry} material={materials['TRANS-BROWN']} position={[-80, -89.054, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.987, 0.969, 0.987]} />
            <mesh geometry={nodes.Base_53.geometry} material={materials['METAL-SILVER']} position={[-60, -89.138, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_54.geometry} material={materials['METAL-SILVER_0']} position={[-60, -89.338, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_55.geometry} material={materials['TRANS-BROWN']} position={[-100, -73.304, 20]} rotation={[0, -Math.PI / 2, 0]} scale={[0.987, 0.984, 0.987]} />
            <mesh geometry={nodes.Base_56.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-69.966, -41.118, 20]} scale={[0.995, 0.984, 0.987]} />
            <mesh geometry={nodes.Base_57.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-0.045, -73.104, 20]} rotation={[0, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_58.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY_0']} position={[-0.045, -73.307, 10.063]} rotation={[0, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_59.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY_0']} position={[-0.045, -73.307, 29.938]} rotation={[0, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_60.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY_0']} position={[-19.932, -65.407, 29.937]} rotation={[0, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_61.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY_0']} position={[-19.932, -65.407, 10.062]} rotation={[0, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_62.geometry} material={materials['SOLID-WHITE']} position={[-20, -73.217, 0]} rotation={[0, Math.PI / 2, 0]} scale={[0.994, 0.989, 0.988]} />
            <mesh geometry={nodes.Base_63.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -73.42, 9.937]} rotation={[0, -Math.PI / 2, 0]} scale={[0.994, 0.989, 0.988]} />
            <mesh geometry={nodes.Base_64.geometry} material={materials['SOLID-WHITE']} position={[-20, -73.217, 40]} rotation={[0, -Math.PI / 2, 0]} scale={[0.994, 0.989, 0.988]} />
            <mesh geometry={nodes.Base_65.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -73.42, 30.062]} rotation={[0, Math.PI / 2, 0]} scale={[0.994, 0.989, 0.988]} />
            <mesh geometry={nodes.Base_66.geometry} material={materials['SOLID-WHITE']} position={[-10.042, -81.138, 20]} rotation={[0, -Math.PI / 2, 0]} scale={[0.994, 0.979, 0.996]} />
            <mesh geometry={nodes.Base_67.geometry} material={materials['SOLID-WHITE_0']} position={[-0.084, -81.338, 10.062]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.996, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_68.geometry} material={materials['SOLID-WHITE_0']} position={[-20.001, -81.338, 10.062]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.996, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_69.geometry} material={materials['SOLID-WHITE_0']} position={[-0.084, -81.338, 29.937]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.996, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_70.geometry} material={materials['SOLID-WHITE_0']} position={[-20.001, -81.338, 29.937]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.996, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_71.geometry} material={materials['SOLID-WHITE']} position={[0, -89.138, 20]} rotation={[0, Math.PI / 2, 0]} scale={[0.994, 0.979, 0.988]} />
            <mesh geometry={nodes.Base_72.geometry} material={materials['SOLID-WHITE']} position={[-20, -89.138, 20]} rotation={[0, Math.PI / 2, 0]} scale={[0.994, 0.979, 0.988]} />
            <mesh geometry={nodes.Base_73.geometry} material={materials['PEARL-DARK_GRAY']} position={[-10, -97.054, 20]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.994, 0.969, 0.988]} />
            <mesh geometry={nodes.Base_74.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-0.046, -41.254, 20]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_75.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY_0']} position={[-0.046, -41.052, 29.937]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_76.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY_0']} position={[-0.046, -41.052, 10.062]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_77.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY_0']} position={[-19.932, -48.952, 10.062]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_78.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY_0']} position={[-19.932, -48.952, 29.937]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.994, 0.988, 0.994]} />
            <mesh geometry={nodes.Base_79.geometry} material={materials['SOLID-DARK_BLUISH_GRAY']} position={[-20.06, -33.242, 20]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[0.994, 0.984, 0.993]} />
            <mesh geometry={nodes.Base_80.geometry} material={materials['SOLID-WHITE']} position={[-20, -41.141, 40]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_81.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -40.939, 30.062]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_82.geometry} material={materials['SOLID-WHITE']} position={[-20, -41.141, 0]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_83.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -40.939, 9.937]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_84.geometry} material={materials['SOLID-WHITE']} position={[0, -33.221, 20]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_85.geometry} material={materials['SOLID-WHITE_0']} position={[0, -33.02, 29.937]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_86.geometry} material={materials['SOLID-WHITE_0']} position={[0, -33.02, 10.062]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[0.994, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_87.geometry} material={materials['SOLID-WHITE']} position={[-10, -25.221, 20]} rotation={[0, 0, -Math.PI]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_88.geometry} material={materials['SOLID-WHITE_0']} position={[-19.938, -25.02, 10.062]} rotation={[0, 0, -Math.PI]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_89.geometry} material={materials['SOLID-WHITE_0']} position={[-0.063, -25.02, 10.062]} rotation={[0, 0, -Math.PI]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_90.geometry} material={materials['SOLID-WHITE_0']} position={[-19.938, -25.02, 29.937]} rotation={[0, 0, -Math.PI]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_91.geometry} material={materials['SOLID-WHITE_0']} position={[-0.063, -25.02, 29.937]} rotation={[0, 0, -Math.PI]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_92.geometry} material={materials['SOLID-WHITE']} position={[17.957, -57.179, 20]} rotation={[0, 0, Math.PI / 2]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_93.geometry} material={materials['SOLID-WHITE_0']} position={[18.158, -47.242, 10.062]} rotation={[0, 0, Math.PI / 2]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_94.geometry} material={materials['SOLID-WHITE_0']} position={[18.158, -67.117, 10.062]} rotation={[0, 0, Math.PI / 2]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_95.geometry} material={materials['SOLID-WHITE_0']} position={[18.158, -47.242, 29.937]} rotation={[0, 0, Math.PI / 2]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_96.geometry} material={materials['SOLID-WHITE_0']} position={[18.158, -67.117, 29.937]} rotation={[0, 0, Math.PI / 2]} scale={[0.994, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_97.geometry} material={materials['SOLID-WHITE']} position={[25.957, -47.179, 20]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.994, 0.979, 0.988]} />
            <mesh geometry={nodes.Base_98.geometry} material={materials['SOLID-WHITE']} position={[25.957, -67.179, 20]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[0.994, 0.979, 0.988]} />
            <mesh geometry={nodes.Base_99.geometry} material={materials['PEARL-DARK_GRAY']} position={[33.874, -57.179, 20]} rotation={[0, 0, Math.PI / 2]} scale={[0.994, 0.969, 0.987]} />
            <mesh geometry={nodes.Base_100.geometry} material={materials['SOLID-WHITE']} position={[-20, -83.086, 101.787]} rotation={[-0.91, 1.57, 1.232]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_101.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -73.046, 73.616]} rotation={[-0.91, 1.57, 1.232]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_102.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -79.865, 92.351]} rotation={[-0.91, 1.57, 1.232]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_103.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -86.684, 111.086]} rotation={[-0.91, 1.57, 1.232]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_104.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -93.503, 129.821]} rotation={[-0.91, 1.57, 1.232]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_105.geometry} material={materials['SOLID-WHITE']} position={[-10, -100.889, 127.287]} rotation={[Math.PI / 9, 0, 0]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_106.geometry} material={materials['SOLID-WHITE_0']} position={[-0.062, -101.079, 127.218]} rotation={[Math.PI / 9, 0, 0]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_107.geometry} material={materials['SOLID-WHITE_0']} position={[-19.937, -101.079, 127.218]} rotation={[Math.PI / 9, 0, 0]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_108.geometry} material={materials['SOLID-WHITE']} position={[10, -83.086, 101.787]} rotation={[Math.PI / 9, 0, 0]} scale={[0.994, 0.979, 0.997]} />
            <mesh geometry={nodes.Base_109.geometry} material={materials['SOLID-WHITE_0']} position={[0.063, -73.046, 73.616]} rotation={[-0.96, 1.57, 1.284]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_110.geometry} material={materials['SOLID-WHITE_0']} position={[0.063, -79.865, 92.351]} rotation={[-0.96, 1.57, 1.284]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_111.geometry} material={materials['SOLID-WHITE_0']} position={[0.063, -86.684, 111.086]} rotation={[-0.96, 1.57, 1.284]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_112.geometry} material={materials['SOLID-WHITE_0']} position={[0.063, -93.503, 129.821]} rotation={[-0.96, 1.57, 1.284]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_113.geometry} material={materials['SOLID-DARK_RED']} position={[-10, -93.945, 108.476]} rotation={[-2.793, 0, -Math.PI]} scale={[0.994, 0.969, 0.987]} />
            <mesh geometry={nodes.Base_114.geometry} material={materials['SOLID-WHITE']} position={[-10, -76.402, 82.936]} rotation={[Math.PI / 9, 0, 0]} scale={[0.994, 0.984, 0.994]} />
            <mesh geometry={nodes.Base_115.geometry} material={materials['SOLID-WHITE']} position={[-20, -80.342, 70.86]} rotation={[-0.91, 1.57, 1.232]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_116.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -80.531, 70.791]} rotation={[-0.91, 1.57, 1.232]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_117.geometry} material={materials['SOLID-WHITE']} position={[0, -76.997, 61.436]} rotation={[-0.91, 1.57, 1.232]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_118.geometry} material={materials['SOLID-WHITE_0']} position={[0, -80.587, 70.705]} rotation={[-0.91, -1.57, -1.232]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_119.geometry} material={materials['SOLID-BLACK']} position={[-10, -79.179, 50]} rotation={[Math.PI / 9, 0, 0]} scale={[0.994, 0.984, 0.984]} />
            <mesh geometry={nodes.Base_120.geometry} material={materials['SOLID-WHITE']} position={[-20, -31.273, -61.787]} rotation={[-0.91, 1.57, -Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_121.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -41.313, -33.616]} rotation={[-0.91, 1.57, -Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_122.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -34.494, -52.351]} rotation={[-0.91, 1.57, -Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_123.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -27.675, -71.086]} rotation={[-0.91, 1.57, -Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_124.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -20.856, -89.821]} rotation={[-0.91, 1.57, -Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_125.geometry} material={materials['SOLID-WHITE']} position={[-10, -13.469, -87.287]} rotation={[-2.793, 0, 0]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_126.geometry} material={materials['SOLID-WHITE_0']} position={[-0.063, -13.28, -87.218]} rotation={[-2.793, 0, 0]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_127.geometry} material={materials['SOLID-WHITE_0']} position={[-19.938, -13.28, -87.218]} rotation={[-2.793, 0, 0]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_128.geometry} material={materials['SOLID-WHITE']} position={[10, -31.273, -61.787]} rotation={[-2.793, 0, 0]} scale={[0.994, 0.979, 0.997]} />
            <mesh geometry={nodes.Base_129.geometry} material={materials['SOLID-WHITE_0']} position={[0.062, -41.313, -33.616]} rotation={[-0.847, 1.57, -1.646]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_130.geometry} material={materials['SOLID-WHITE_0']} position={[0.062, -34.494, -52.351]} rotation={[-0.847, 1.57, -1.646]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_131.geometry} material={materials['SOLID-WHITE_0']} position={[0.062, -27.675, -71.086]} rotation={[-0.847, 1.57, -1.646]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_132.geometry} material={materials['SOLID-WHITE_0']} position={[0.062, -20.856, -89.821]} rotation={[-0.847, 1.57, -1.646]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_133.geometry} material={materials['SOLID-DARK_RED']} position={[-10, -20.414, -68.476]} rotation={[Math.PI / 9, 0, Math.PI]} scale={[0.994, 0.969, 0.987]} />
            <mesh geometry={nodes.Base_134.geometry} material={materials['SOLID-WHITE']} position={[-10, -37.957, -42.936]} rotation={[-2.793, 0, 0]} scale={[0.994, 0.984, 0.994]} />
            <mesh geometry={nodes.Base_135.geometry} material={materials['SOLID-WHITE']} position={[-20, -34.016, -30.86]} rotation={[-0.91, 1.57, -Math.PI / 2]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_136.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -33.828, -30.792]} rotation={[-0.91, 1.57, -Math.PI / 2]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_137.geometry} material={materials['SOLID-WHITE']} position={[0, -37.362, -21.436]} rotation={[-0.91, 1.57, -Math.PI / 2]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_138.geometry} material={materials['SOLID-WHITE_0']} position={[0, -33.772, -30.705]} rotation={[-0.91, -1.57, Math.PI / 2]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_139.geometry} material={materials['SOLID-BLACK']} position={[-10, -35.179, -10]} rotation={[-2.793, 0, 0]} scale={[0.994, 0.984, 0.984]} />
            <mesh geometry={nodes.Base_140.geometry} material={materials['SOLID-WHITE']} position={[-20, -31.273, 101.787]} rotation={[0.91, 1.57, Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_141.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -20.856, 129.82]} rotation={[0.91, 1.57, Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_142.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -27.675, 111.085]} rotation={[0.91, 1.57, Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_143.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -34.494, 92.35]} rotation={[0.91, 1.57, Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_144.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -41.313, 73.615]} rotation={[0.91, 1.57, Math.PI / 2]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_145.geometry} material={materials['SOLID-WHITE']} position={[-10, -13.469, 127.287]} rotation={[-Math.PI / 9, 0, -Math.PI]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_146.geometry} material={materials['SOLID-WHITE_0']} position={[-19.937, -13.28, 127.218]} rotation={[-Math.PI / 9, 0, -Math.PI]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_147.geometry} material={materials['SOLID-WHITE_0']} position={[-0.063, -13.28, 127.218]} rotation={[-Math.PI / 9, 0, -Math.PI]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_148.geometry} material={materials['SOLID-WHITE']} position={[10, -31.273, 101.787]} rotation={[-Math.PI / 9, 0, -Math.PI]} scale={[0.994, 0.979, 0.997]} />
            <mesh geometry={nodes.Base_149.geometry} material={materials['SOLID-WHITE_0']} position={[0.062, -41.313, 73.615]} rotation={[-2.133, -1.57, 1.071]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_150.geometry} material={materials['SOLID-WHITE_0']} position={[0.062, -34.494, 92.35]} rotation={[-2.133, -1.57, 1.071]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_151.geometry} material={materials['SOLID-WHITE_0']} position={[0.062, -27.675, 111.085]} rotation={[-2.133, -1.57, 1.071]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_152.geometry} material={materials['SOLID-WHITE_0']} position={[0.062, -20.856, 129.82]} rotation={[-2.133, -1.57, 1.071]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_153.geometry} material={materials['SOLID-DARK_RED']} position={[-10, -20.414, 108.476]} rotation={[-Math.PI / 9, 0, -Math.PI]} scale={[0.994, 0.969, 0.987]} />
            <mesh geometry={nodes.Base_154.geometry} material={materials['SOLID-WHITE']} position={[0, -37.361, 61.436]} rotation={[0.91, -1.57, -Math.PI / 2]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_155.geometry} material={materials['SOLID-WHITE_0']} position={[0, -33.772, 70.705]} rotation={[0.91, 1.57, Math.PI / 2]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_156.geometry} material={materials['SOLID-WHITE']} position={[-20, -34.016, 70.86]} rotation={[-Math.PI / 9, 0, -Math.PI]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_157.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -33.828, 70.791]} rotation={[-Math.PI / 9, 0, -Math.PI]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_158.geometry} material={materials['SOLID-WHITE']} position={[-10, -37.957, 82.936]} rotation={[-Math.PI / 9, 0, -Math.PI]} scale={[0.994, 0.984, 0.994]} />
            <mesh geometry={nodes.Base_159.geometry} material={materials['SOLID-BLACK']} position={[-10, -35.179, 50]} rotation={[-0.175, 0, -Math.PI]} scale={[0.994, 0.984, 0.984]} />
            <mesh geometry={nodes.Base_160.geometry} material={materials['SOLID-WHITE']} position={[-20, -83.085, -61.787]} rotation={[1.456, 1.57, -1.809]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_161.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -93.503, -89.82]} rotation={[1.456, 1.57, -1.809]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_162.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -86.684, -71.086]} rotation={[1.456, 1.57, -1.809]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_163.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -79.865, -52.351]} rotation={[1.456, 1.57, -1.809]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_164.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -73.046, -33.616]} rotation={[1.456, 1.57, -1.809]} scale={[0.997, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_165.geometry} material={materials['SOLID-WHITE']} position={[-10, -100.889, -87.287]} rotation={[2.793, 0, -Math.PI]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_166.geometry} material={materials['SOLID-WHITE_0']} position={[-19.937, -101.079, -87.218]} rotation={[2.793, 0, -Math.PI]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_167.geometry} material={materials['SOLID-WHITE_0']} position={[-0.062, -101.079, -87.218]} rotation={[2.793, 0, -Math.PI]} scale={[0.994, 0.983, 0.993]} />
            <mesh geometry={nodes.Base_168.geometry} material={materials['SOLID-WHITE']} position={[10, -83.086, -61.787]} rotation={[2.793, 0, -Math.PI]} scale={[0.994, 0.979, 0.997]} />
            <mesh geometry={nodes.Base_169.geometry} material={materials['SOLID-WHITE_0']} position={[0.063, -73.046, -33.616]} rotation={[0.857, -1.57, 1.177]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_170.geometry} material={materials['SOLID-WHITE_0']} position={[0.063, -79.865, -52.351]} rotation={[0.857, -1.57, 1.177]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_171.geometry} material={materials['SOLID-WHITE_0']} position={[0.063, -86.684, -71.086]} rotation={[0.857, -1.57, 1.177]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_172.geometry} material={materials['SOLID-WHITE_0']} position={[0.063, -93.503, -89.821]} rotation={[0.857, -1.57, 1.177]} scale={[0.997, 0.979, 0.994]} />
            <mesh geometry={nodes.Base_173.geometry} material={materials['SOLID-DARK_RED']} position={[-10, -93.945, -68.476]} rotation={[2.793, 0, -Math.PI]} scale={[0.994, 0.969, 0.987]} />
            <mesh geometry={nodes.Base_174.geometry} material={materials['SOLID-WHITE']} position={[0, -76.997, -21.436]} rotation={[0.528, -1.57, 0.842]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_175.geometry} material={materials['SOLID-WHITE_0']} position={[0, -80.587, -30.705]} rotation={[1.523, 1.57, -1.879]} scale={[0.994, 0.989, 0.987]} />
            <mesh geometry={nodes.Base_176.geometry} material={materials['SOLID-WHITE']} position={[-20, -80.342, -30.86]} rotation={[2.793, 0, -Math.PI]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_177.geometry} material={materials['SOLID-WHITE_0']} position={[-20, -80.531, -30.792]} rotation={[2.793, 0, -Math.PI]} scale={[0.987, 0.979, 0.987]} />
            <mesh geometry={nodes.Base_178.geometry} material={materials['SOLID-WHITE']} position={[-10, -76.402, -42.936]} rotation={[2.793, 0, -Math.PI]} scale={[0.994, 0.984, 0.994]} />
            <mesh geometry={nodes.Base_179.geometry} material={materials['SOLID-BLACK']} position={[-10, -79.179, -10]} rotation={[2.793, 0, -Math.PI]} scale={[0.994, 0.984, 0.984]} />
            <mesh geometry={nodes.Base_180.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[10.1, -35.179, 50]} rotation={[-0.175, 0, -Math.PI / 2]} scale={[0.984, 0.994, 0.984]} />
            <mesh geometry={nodes.Base_181.geometry} material={materials['SOLID-BLACK']} position={[-44.575, -35.179, 50]} rotation={[-0.175, 0, -Math.PI / 2]} scale={[0.969, 0.996, 0.969]} />
            <mesh geometry={nodes.Base_182.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[10.1, -79.179, 50]} rotation={[1.92, 0, -Math.PI / 2]} scale={[0.984, 0.994, 0.984]} />
            <mesh geometry={nodes.Base_183.geometry} material={materials['SOLID-BLACK']} position={[-44.575, -79.179, 50]} rotation={[1.92, 0, -Math.PI / 2]} scale={[0.969, 0.996, 0.969]} />
            <mesh geometry={nodes.Base_184.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[10.1, -79.179, -10]} rotation={[-Math.PI / 9, 0, -Math.PI / 2]} scale={[0.984, 0.994, 0.984]} />
            <mesh geometry={nodes.Base_185.geometry} material={materials['SOLID-BLACK']} position={[-44.575, -79.179, -10]} rotation={[-Math.PI / 9, 0, -Math.PI / 2]} scale={[0.969, 0.996, 0.969]} />
            <mesh geometry={nodes.Base_186.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[10.1, -35.179, -10]} rotation={[Math.PI / 9, 0, -Math.PI / 2]} scale={[0.984, 0.994, 0.984]} />
            <mesh geometry={nodes.Base_187.geometry} material={materials['SOLID-BLACK']} position={[-44.575, -35.179, -10]} rotation={[Math.PI / 9, 0, -Math.PI / 2]} scale={[0.969, 0.996, 0.969]} />
            <mesh geometry={nodes.Base_188.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-49.61, -79.179, 50]} rotation={[0, 0, -Math.PI / 2]} scale={[0.988, 0.991, 0.987]} />
            <mesh geometry={nodes.Base_189.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-49.911, -35.179, 50]} rotation={[-0.175, 0, -Math.PI / 2]} scale={[0.988, 0.991, 0.987]} />
            <mesh geometry={nodes.Base_190.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-49.61, -79.179, -10]} rotation={[0, 0, -Math.PI / 2]} scale={[0.988, 0.991, 0.987]} />
            <mesh geometry={nodes.Base_191.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-49.611, -35.179, -10]} rotation={[0, 0, -Math.PI / 2]} scale={[0.988, 0.991, 0.987]} />
            <mesh geometry={nodes.Base_192.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-31.4, -8.495, -106.705]} rotation={[0, 0, -Math.PI / 2]} scale={[0.984, 0.994, 0.984]} />
            <mesh geometry={nodes.Base_193.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-219.937, -49.104, 20]} rotation={[0, -Math.PI / 2, 0]} scale={[0.987, 0.987, 0.994]} />
            <mesh geometry={nodes.Base_194.geometry} material={materials['SOLID-DARK_BLUISH_GRAY']} position={[-23.555, -8.495, -106.705]} rotation={[0, 0, Math.PI / 2]} scale={[0.979, 0.996, 0.979]} />
            <mesh geometry={nodes.Base_195.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-31.4, -8.495, 146.705]} rotation={[-0.175, 0, -Math.PI / 2]} scale={[0.984, 0.994, 0.984]} />
            <mesh geometry={nodes.Base_196.geometry} material={materials['SOLID-DARK_BLUISH_GRAY']} position={[-23.555, -8.495, 146.705]} rotation={[-0.175, 0, Math.PI / 2]} scale={[0.979, 0.996, 0.979]} />
            <mesh geometry={nodes.Base_197.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-31.4, -105.864, 146.705]} rotation={[0, 0, -Math.PI / 2]} scale={[0.984, 0.994, 0.984]} />
            <mesh geometry={nodes.Base_198.geometry} material={materials['SOLID-DARK_BLUISH_GRAY']} position={[-23.555, -105.864, 146.705]} rotation={[0, 0, Math.PI / 2]} scale={[0.979, 0.996, 0.979]} />
            <mesh geometry={nodes.Base_199.geometry} material={materials['SOLID-LIGHT_BLUISH_GRAY']} position={[-31.4, -105.864, -106.705]} rotation={[0, 0, -Math.PI / 2]} scale={[0.984, 0.994, 0.984]} />
            <mesh geometry={nodes.Base_200.geometry} material={materials['SOLID-DARK_BLUISH_GRAY']} position={[-23.555, -105.864, -106.705]} rotation={[0, 0, Math.PI / 2]} scale={[0.979, 0.996, 0.979]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/30654_-_x-wing_starfighter.glb')
